{% set name = "types-characteristic" %}
{% set version = "14.3.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/types-characteristic-{{ version }}.tar.gz
  sha256: 345e03675b8df87d62f894d7b7c0f7953e7b425f714f33506f85f00dc72449a3

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  commands:
    - test -f $SP_DIR/characteristic-stubs/__init__.pyi


about:
  home: https://github.com/python/typeshed
  summary: Typing stubs for characteristic
  license: Apache-2.0 AND MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - fhoehle
    - conda-forge/mypy
