{% set version = "14.3.7" %}

package:
  name: types-characteristic
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/t/types-characteristic/types-characteristic-{{ version }}.tar.gz
  sha256: de01956d96521389a9bc670b8fab49fd9602ed5def29af5744452455ef446bc7

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}

test:
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check
    - test -f $SP_DIR/characteristic-stubs/__init__.pyi

about:
  home: https://github.com/python/typeshed
  summary: Typing stubs for characteristic
  license: Apache-2.0 AND MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - fhoehle
    - conda-forge/mypy
