{% set name = "types-characteristic" %}
{% set version = "14.3.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/types-characteristic-{{ version }}.tar.gz
  sha256: f74b9b55d2d71419728783da9a58bd15cfb06c8ce63369b63cf381ee91e831d6

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  commands:
    - test -f $SP_DIR/characteristic-stubs/__init__.pyi


about:
  home: https://github.com/python/typeshed
  summary: Typing stubs for characteristic
  license: Apache-2.0 AND MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - fhoehle
    - conda-forge/mypy
